const positions=['Ketua','Wakil Ketua','Sekretaris','Bendahara','Kepala Bidang Kajian Kepramukaan','Kepala Bidang Kegiatan','Kepala Bidang Pembinaan dan Pengembangan','Kepala Bidang Penelitian dan Evaluasi','Anggota Bidang Kajian Kepramukaan','Anggota Bidang Kegiatan','Anggota Bidang Pembinaan dan Pengembangan','Anggota Bidang Penelitian dan Evaluasi'];
const members=positions.map((position,i)=>({position,name:'Nama Pengurus',bio:'Biodata singkat pengurus akan diperbarui melalui panel pengelola.',photo:''}));
const info=[{title:'Informasi DKC Bantul',date:'',time:'',venue:'',notes:'Belum ada publikasi terbaru. Konten akan dikelola melalui panel admin.'}];
const activities=[{title:'Kegiatan DKC Bantul',date:'',time:'',venue:'',notes:'Dokumentasi kegiatan akan ditampilkan di halaman ini.'}];
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v){if(!v)return 'Tanggal menyusul';return new Date(v+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'})}
function nav(){const menu=document.querySelector('.menu'),links=document.querySelector('.navlinks');if(menu)menu.onclick=()=>links.classList.toggle('open');document.querySelectorAll('.navlinks a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));const page=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.navlinks a[data-page]').forEach(a=>{if(a.dataset.page===page)a.classList.add('active')})}
function renderMembers(){const root=document.getElementById('members');if(!root)return;root.innerHTML=members.map((m,i)=>`<article class="person ${i===0?'leader':''}"><div class="person-top">${m.photo?`<img src="${m.photo}" alt="${esc(m.name)}" style="width:100%;height:100%;object-fit:contain">`:'<div class="placeholder">◎</div>'}</div><div class="person-body"><small>${esc(m.position)}</small><h3>${esc(m.name)}</h3><p>${esc(m.bio)}</p></div></article>`).join('')}
function renderEvents(id,data,activity=false){const root=document.getElementById(id);if(!root)return;root.innerHTML=data.map(x=>activity?`<article class="activity"><div class="activity-cover">✦</div><div class="activity-body"><h3>${esc(x.title)}</h3><div class="meta"><span>${fmtDate(x.date)}</span>${x.time?`<span>${esc(x.time)} WIB</span>`:''}${x.venue?`<span>${esc(x.venue)}</span>`:''}</div><p>${esc(x.notes||'')}</p></div></article>`:`<article class="event"><div><h3>${esc(x.title)}</h3><div class="meta"><span>${fmtDate(x.date)}</span>${x.time?`<span>${esc(x.time)} WIB</span>`:''}${x.venue?`<span>${esc(x.venue)}</span>`:''}</div><p>${esc(x.notes||'')}</p></div></article>`).join('')}
function saveSuggestion(e){e.preventDefault();const f=e.target;const all=JSON.parse(localStorage.getItem('dkc_suggestions')||'[]');all.push({date:new Date().toISOString(),nama:f.nama.value,pangkalan:f.pangkalan.value,saran:f.saran.value});localStorage.setItem('dkc_suggestions',JSON.stringify(all));const s=document.getElementById('status');if(s)s.textContent='Terima kasih. Usul dan saran Anda telah tercatat pada perangkat ini.';f.reset();const count=document.getElementById('count');if(count)count.textContent=all.length}
function initSuggestion(){const f=document.getElementById('suggestionForm');if(f)f.addEventListener('submit',saveSuggestion);const count=document.getElementById('count');if(count)count.textContent=JSON.parse(localStorage.getItem('dkc_suggestions')||'[]').length}
function exportExcel(){const all=JSON.parse(localStorage.getItem('dkc_suggestions')||'[]');let html='<table><tr><th>Tanggal</th><th>Nama</th><th>Pangkalan/Ranting</th><th>Usul/Saran</th></tr>'+all.map(x=>`<tr><td>${fmtDate(x.date.slice(0,10))}</td><td>${esc(x.nama)}</td><td>${esc(x.pangkalan)}</td><td>${esc(x.saran)}</td></tr>`).join('')+'</table>';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff',html],{type:'application/vnd.ms-excel'}));a.download='rekap-usul-saran-dkc-bantul.xls';a.click()}
function exportPDF(){const all=JSON.parse(localStorage.getItem('dkc_suggestions')||'[]');const w=window.open('','_blank');w.document.write(`<html><head><title>Rekap Usul & Saran DKC Bantul</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aaa;padding:8px;text-align:left}h1{font-size:20px}</style></head><body><h1>Rekap Usul & Saran — DKC Bantul</h1><table><tr><th>Tanggal</th><th>Nama</th><th>Pangkalan/Ranting</th><th>Usul/Saran</th></tr>${all.map(x=>`<tr><td>${fmtDate(x.date.slice(0,10))}</td><td>${esc(x.nama)}</td><td>${esc(x.pangkalan)}</td><td>${esc(x.saran)}</td></tr>`).join('')}</table><script>window.print()<\/script></body></html>`);w.document.close()}
function init(){nav();renderMembers();renderEvents('infoList',info);renderEvents('activityList',activities,true);initSuggestion();const ex=document.getElementById('exportExcel');if(ex)ex.onclick=exportExcel;const ep=document.getElementById('exportPDF');if(ep)ep.onclick=exportPDF}
document.addEventListener('DOMContentLoaded',init);
