const POSITIONS=['Ketua','Wakil Ketua','Sekretaris','Bendahara','Kepala Bidang Kajian Kepramukaan','Kepala Bidang Kegiatan','Kepala Bidang Pembinaan dan Pengembangan','Kepala Bidang Penelitian dan Evaluasi','Anggota Bidang Kajian Kepramukaan','Anggota Bidang Kegiatan','Anggota Bidang Pembinaan dan Pengembangan','Anggota Bidang Penelitian dan Evaluasi'];
const defaultMembers=POSITIONS.map((position,i)=>({id:'m'+i,name:'Nama Pengurus',position,bio:'Biodata singkat pengurus dapat diperbarui melalui menu Kelola.',photo:''}));
const state={members:load('members',defaultMembers),programs:load('programs',[{id:'p1',title:'Program Kerja DKC Bantul 2026–2031',description:'Dokumen induk program kerja dan arah pelaksanaan kegiatan Dewan Kerja.',estimate:'2026–2031',pdf:''}]),infos:load('infos',[]),activities:load('activities',[]),suggestions:load('suggestions',[])};
function load(k,f){try{const v=JSON.parse(localStorage.getItem('dkc_'+k));return v??f}catch(e){return f}}
function save(k,v){try{localStorage.setItem('dkc_'+k,JSON.stringify(v))}catch(e){alert('Penyimpanan browser penuh. Untuk file PDF berukuran besar, gunakan versi produksi dengan server/storage.')}}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fmtDate(v){if(!v)return 'Tanggal belum diisi';return new Date(v+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'long',year:'numeric'})}
function dataURL(file){return new Promise((res,rej)=>{if(!file)return res('');const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function renderMembers(){const root=document.getElementById('structureGrid');root.innerHTML=state.members.map((m,i)=>`<article class="member-card"><div class="member-photo">${m.photo?`<img src="${m.photo}" alt="${esc(m.name)}">`:'<div class="member-placeholder">◎</div>'}</div><div class="member-info"><div class="member-position">${esc(m.position)}</div><div class="member-name">${esc(m.name)}</div><p class="member-bio">${esc(m.bio)}</p></div></article>`).join('')}
function renderPrograms(){const root=document.getElementById('programList');root.innerHTML=state.programs.length?state.programs.map(p=>`<article class="program-item"><div><h3>${esc(p.title)}</h3><p>${esc(p.description)}</p><div class="program-estimate">Estimasi: ${esc(p.estimate||'Belum ditentukan')}</div></div>${p.pdf?`<button class="book-btn" onclick="openPdf('${p.pdf}','${esc(p.title)}')">Baca seperti buku</button>`:'<span class="chip">Dokumen belum diunggah</span>'}</article>`).join(''):'<div class="card" style="padding:25px">Belum ada program kerja.</div>'}
function docs(x){let out='';[['attachment','Lampiran acara'],['circular','Surat edaran'],['guide','Juklak/Juknis']].forEach(([k,l])=>{if(x[k])out+=`<button class="doc-btn" onclick="openPdf('${x[k]}','${esc(l)}')">${l}</button>`});return out}
function eventCard(x,activity=false){return `<article class="${activity?'activity-card':'info-card'}">${activity?'<div class="activity-top">✦</div>':''}<div class="${activity?'activity-body':''}"><h3>${esc(x.title)}</h3><div class="info-meta"><span class="chip">${fmtDate(x.date)}</span>${x.time?`<span class="chip">${esc(x.time)} WIB</span>`:''}${x.venue?`<span class="chip">${esc(x.venue)}</span>`:''}</div>${x.location?`<p>📍 ${esc(x.location)}</p>`:''}${x.notes?`<p>${esc(x.notes)}</p>`:''}<div class="doc-row">${x.registration?`<a class="register-btn" target="_blank" rel="noopener" href="${esc(x.registration)}">Pendaftaran</a>`:''}${docs(x)}</div></div></article>`}
function renderInfos(){document.getElementById('infoList').innerHTML=state.infos.length?state.infos.map(x=>eventCard(x,false)).join(''):'<div class="card" style="padding:25px">Belum ada informasi terkini. Tambahkan melalui menu Kelola.</div>'}
function renderActivities(){document.getElementById('activityList').innerHTML=state.activities.length?state.activities.map(x=>eventCard(x,true)).join(''):'<div class="card" style="padding:25px;grid-column:1/-1">Belum ada kegiatan terkini. Tambahkan melalui menu Kelola.</div>'}
function renderAll(){renderMembers();renderPrograms();renderInfos();renderActivities();renderAdminLists();document.getElementById('suggestionCount').textContent=state.suggestions.length}
window.openPdf=(src,title)=>{document.getElementById('pdfTitle').textContent=title;document.getElementById('pdfFrame').src=src;document.getElementById('pdfDialog').showModal()};
const pdfDialog=document.getElementById('pdfDialog');document.getElementById('pdfClose').onclick=()=>pdfDialog.close();
document.getElementById('menuToggle').onclick=()=>document.getElementById('mainNav').classList.toggle('open');
document.querySelectorAll('#mainNav a').forEach(a=>a.onclick=()=>document.getElementById('mainNav').classList.remove('open'));
const admin=document.getElementById('adminDialog');document.getElementById('adminOpen').onclick=()=>admin.showModal();document.getElementById('adminClose').onclick=()=>admin.close();
document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tabs button,.admin-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
const sel=document.querySelector('#memberForm select[name=position]');sel.innerHTML='<option value="">Pilih jabatan</option>'+POSITIONS.map(p=>`<option>${p}</option>`).join('');
function renderAdminLists(){document.getElementById('memberAdminList').innerHTML=state.members.map((m,i)=>`<div class="admin-item"><div><strong>${esc(m.position)}</strong><small>${esc(m.name)}</small></div><button class="danger" onclick="removeMember(${i})">Hapus</button></div>`).join('');document.getElementById('programAdminList').innerHTML=state.programs.map((p,i)=>`<div class="admin-item"><div><strong>${esc(p.title)}</strong><small>${esc(p.estimate)}</small></div><button class="danger" onclick="removeProgram(${i})">Hapus</button></div>`).join('');document.getElementById('infoAdminList').innerHTML=state.infos.map((p,i)=>`<div class="admin-item"><div><strong>${esc(p.title)}</strong><small>${fmtDate(p.date)}</small></div><button class="danger" onclick="removeInfo(${i})">Hapus</button></div>`).join('');document.getElementById('activityAdminList').innerHTML=state.activities.map((p,i)=>`<div class="admin-item"><div><strong>${esc(p.title)}</strong><small>${fmtDate(p.date)}</small></div><button class="danger" onclick="removeActivity(${i})">Hapus</button></div>`).join('')}
window.removeMember=i=>{state.members.splice(i,1);save('members',state.members);renderAll()};window.removeProgram=i=>{state.programs.splice(i,1);save('programs',state.programs);renderAll()};window.removeInfo=i=>{state.infos.splice(i,1);save('infos',state.infos);renderAll()};window.removeActivity=i=>{state.activities.splice(i,1);save('activities',state.activities);renderAll()};
document.getElementById('memberForm').onsubmit=async e=>{e.preventDefault();const f=e.target;state.members.push({id:crypto.randomUUID(),name:f.name.value,position:f.position.value,bio:f.bio.value,photo:await dataURL(f.photo.files[0])});save('members',state.members);f.reset();renderAll()};
document.getElementById('programForm').onsubmit=async e=>{e.preventDefault();const f=e.target;state.programs.push({id:crypto.randomUUID(),title:f.title.value,description:f.description.value,estimate:f.estimate.value,pdf:await dataURL(f.pdf.files[0])});save('programs',state.programs);f.reset();renderAll()};
async function submitEvent(form,key){const f=form;const x={id:crypto.randomUUID(),title:f.title.value,date:f.date.value,time:f.time.value,venue:f.venue.value,location:f.location.value,registration:f.registration.value,notes:f.notes.value,attachment:await dataURL(f.attachment.files[0]),circular:await dataURL(f.circular.files[0]),guide:await dataURL(f.guide.files[0])};state[key].push(x);save(key,state[key]);f.reset();renderAll()}
document.getElementById('infoForm').onsubmit=async e=>{e.preventDefault();await submitEvent(e.target,'infos')};document.getElementById('activityForm').onsubmit=async e=>{e.preventDefault();await submitEvent(e.target,'activities')};
document.getElementById('suggestionForm').onsubmit=e=>{e.preventDefault();const f=e.target;state.suggestions.push({id:crypto.randomUUID(),date:new Date().toISOString(),nama:f.nama.value,pangkalan:f.pangkalan.value,saran:f.saran.value});save('suggestions',state.suggestions);f.reset();document.getElementById('suggestionStatus').textContent='Terima kasih. Usul dan saran Anda sudah tercatat di perangkat ini.';document.getElementById('suggestionCount').textContent=state.suggestions.length};
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.getElementById('exportExcel').onclick=()=>{let html='<table><tr><th>Tanggal</th><th>Nama</th><th>Pangkalan/Ranting</th><th>Usul/Saran</th></tr>'+state.suggestions.map(s=>`<tr><td>${fmtDate(s.date?.slice(0,10))}</td><td>${esc(s.nama)}</td><td>${esc(s.pangkalan)}</td><td>${esc(s.saran)}</td></tr>`).join('')+'</table>';downloadBlob(new Blob(['\ufeff',html],{type:'application/vnd.ms-excel'}),'rekap-usul-saran-dkc-bantul.xls')};
document.getElementById('exportPDF').onclick=()=>{const w=window.open('','_blank');w.document.write('<html><head><title>Rekap Usul Saran DKC Bantul</title><style>body{font-family:Arial;padding:30px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aaa;padding:8px;text-align:left}h1{font-size:20px}</style></head><body><h1>Rekap Usul & Saran — DKC Bantul</h1><table><tr><th>Tanggal</th><th>Nama</th><th>Pangkalan/Ranting</th><th>Usul/Saran</th></tr>'+state.suggestions.map(s=>`<tr><td>${fmtDate(s.date?.slice(0,10))}</td><td>${esc(s.nama)}</td><td>${esc(s.pangkalan)}</td><td>${esc(s.saran)}</td></tr>`).join('')+'</table><script>window.print()<\/script></body></html>');w.document.close()};
renderAll();
